services:
  sonata.admin.post:
          class: BlogBundle\Admin\PostAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "Блог", label: "Записи блога" }
          arguments:
              - ~
              - BlogBundle\Entity\Post
              - ~
          calls:
              - [ setTranslationDomain, [SonataAdminBundle]]