services:
  sonata.admin.mainpage:
          class: AppBundle\Admin\MainPageAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "Настройки содержимого", label: "Главная станица" }
          arguments:
              - ~
              - AppBundle\Entity\MainPage
              - ~
          calls:
              - [ setTranslationDomain, [SonataAdminBundle]]

  sonata.admin.service:
          class: AppBundle\Admin\ServiceAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "Настройки содержимого", label: "Услуги" }
          arguments:
              - ~
              - AppBundle\Entity\Service
              - ~
          calls:
              - [ setTranslationDomain, [SonataAdminBundle]]