services:
  sonata.admin.feedback_post:
          class: FeedbackBundle\Admin\FeedbackPostAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "Отзывы", label: "Отзывы" }
          arguments:
              - ~
              - FeedbackBundle\Entity\FeedbackPost
              - ~
          calls:
              - [ setTranslationDomain, [SonataAdminBundle]]

  sonata.admin.feedback_comment:
          class: FeedbackBundle\Admin\FeedbackCommentAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "Отзывы", label: "Комментарии" }
          arguments:
              - ~
              - FeedbackBundle\Entity\FeedbackComment
              - ~
          calls:
              - [ setTranslationDomain, [SonataAdminBundle]]